name: Test React/Next App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: prettier -w .

      - name: Build tha app
        run: npm run build

      - name: Build tha app
        run: npm run build